version: "3"

services:

  flask:
    build: ./flask
    container_name: template_flask
    restart: always
    environment:
      - APP_NAME=FlaskApp
      - CHANNEL_ACCESS_TOKEN=${CHANNEL_ACCESS_TOKEN}
      - CHANNEL_SECRET=${CHANNEL_SECRET}
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    container_name: template_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - flask